/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: da8cb485a581631a37f1052002ee1be2)
interface __BaseEnv_Env {
	FILES: R2Bucket;
	DB: D1Database;
	ENVIRONMENT: "production";
	VERSION: "R0.2.1";
	UPLOAD_MAX_BYTES: "26214400";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "VERSION" | "UPLOAD_MAX_BYTES">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}