DROP TRIGGER enforce_state;
CREATE TRIGGER enforce_state BEFORE UPDATE OF status ON tasks
WHEN OLD.status <> NEW.status AND NOT (
 (OLD.status='REQUESTED' AND NEW.status='ASSIGNED') OR
 (OLD.status='ASSIGNED' AND NEW.status='ACCEPTED') OR
 (OLD.status='ACCEPTED' AND NEW.status='IN_PROGRESS') OR
 (OLD.status='IN_PROGRESS' AND NEW.status='SUBMITTED') OR
 (OLD.status='SUBMITTED' AND NEW.status IN ('VERIFIED','IN_PROGRESS','COMPLETED')) OR
 (OLD.status='VERIFIED' AND NEW.status='COMPLETED')
) BEGIN SELECT RAISE(ABORT,'INVALID_TRANSITION'); END;
