import {fail} from './http.ts';
// Container validation is intentionally separate from MIME sniffing. This rejects
// truncated/header-only uploads; it is not transcoding or full codec verification.
const ascii=(b:Uint8Array,start:number,length:number)=>new TextDecoder().decode(b.subarray(start,start+length));
const be32=(b:Uint8Array,p:number)=>new DataView(b.buffer,b.byteOffset,b.byteLength).getUint32(p);
function valid(condition:unknown){if(!condition)fail(415,'파일이 손상되었거나 미디어 데이터가 없습니다. 원본 파일을 다시 선택해 주세요.');}
function crc32(bytes:Uint8Array){let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let n=0;n<8;n++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
function png(b:Uint8Array){let pos=8,header=false,image=false,end=false;while(pos+12<=b.length){const size=be32(b,pos);valid(size<=b.length-pos-12);const type=ascii(b,pos+4,4);valid(crc32(b.subarray(pos+4,pos+8+size))===be32(b,pos+8+size));if(!header){valid(type==='IHDR'&&size===13);const w=be32(b,pos+8),h=be32(b,pos+12);valid(w>0&&h>0&&w*h<=80000000);header=true;}if(type==='IDAT'&&size>0)image=true;if(type==='IEND'){valid(size===0);end=true;pos+=12;break;}pos+=12+size;}valid(header&&image&&end&&pos===b.length);}
function jpeg(b:Uint8Array){valid(b.length>20&&b[0]===255&&b[1]===216);let pos=2,frame=false,scan=false,quant=false,entropy=0,end=false;while(pos<b.length){valid(b[pos++]===255);while(b[pos]===255)pos++;const marker=b[pos++];if(marker===217){end=true;break;}valid(marker!==0&&pos+2<=b.length);if(marker>=208&&marker<=215)continue;const length=(b[pos]<<8)|b[pos+1];valid(length>=2&&pos+length<=b.length);if(marker===219)quant=true;if([192,193,194,195,197,198,199,201,202,203,205,206,207].includes(marker)){valid(length>=8);const h=(b[pos+3]<<8)|b[pos+4],w=(b[pos+5]<<8)|b[pos+6];valid(w>0&&h>0&&w*h<=80000000);frame=true;}pos+=length;if(marker===218){scan=true;while(pos<b.length){if(b[pos]!==255){entropy++;pos++;continue;}const next=b[pos+1];if(next===0||(next>=208&&next<=215)){entropy++;pos+=2;continue;}break;}}}valid(frame&&scan&&quant&&entropy>0&&end);}
function mp4(b:Uint8Array){const seen=new Set<string>();function boxes(start:number,end:number,depth:number){valid(depth<8);let p=start;while(p+8<=end){let size=be32(b,p),header=8;const type=ascii(b,p+4,4);if(size===1){valid(p+16<=end);const n=new DataView(b.buffer,b.byteOffset,b.byteLength).getBigUint64(p+8);valid(n<=BigInt(Number.MAX_SAFE_INTEGER));size=Number(n);header=16;}if(size===0)size=end-p;valid(size>=header&&p+size<=end);seen.add(type);if(type==='mdat')valid(size>header);if(['moov','trak','mdia','minf','stbl','moof','traf'].includes(type))boxes(p+header,p+size,depth+1);p+=size;}valid(p===end);}boxes(0,b.length,0);valid(seen.has('ftyp')&&seen.has('moov')&&seen.has('trak')&&seen.has('mdia')&&seen.has('mdat'));}
function webp(b:Uint8Array){valid(b.length>=30&&ascii(b,0,4)==='RIFF'&&ascii(b,8,4)==='WEBP');const view=new DataView(b.buffer,b.byteOffset,b.byteLength);valid(view.getUint32(4,true)+8===b.length);let p=12,image=false;while(p+8<=b.length){const type=ascii(b,p,4),size=view.getUint32(p+4,true);valid(size>0&&p+8+size<=b.length);if(type==='VP8 '){valid(size>=10&&b[p+11]===157&&b[p+12]===1&&b[p+13]===42);image=true;}if(type==='VP8L'){valid(size>=5&&b[p+8]===47);image=true;}if(type==='ANMF'){valid(size>16);image=true;}p+=8+size+(size%2);}valid(image&&p===b.length);}
function webm(b:Uint8Array){valid(b.length>64&&be32(b,0)===0x1a45dfa3);let segment=false,tracks=false,cluster=false,video=false;for(let i=4;i+4<=b.length;i++){const id=be32(b,i);if(id===0x18538067)segment=true;if(id===0x1654ae6b)tracks=true;if(id===0x1f43b675&&i+8<b.length)cluster=true;if(ascii(b,i,3)==='V_V'||ascii(b,i,4)==='V_AV')video=true;}valid(segment&&tracks&&cluster&&video);}
export function validateMedia(data:ArrayBuffer,mime:string){const b=new Uint8Array(data);try{if(mime==='image/png')png(b);else if(mime==='image/jpeg')jpeg(b);else if(mime==='image/webp')webp(b);else if(mime==='video/mp4')mp4(b);else if(mime==='video/webm')webm(b);else valid(false);}catch{fail(415,'파일이 손상되었거나 미디어 데이터가 없습니다. 원본 파일을 다시 선택해 주세요.');}}
