import {type Actor,requireRole} from './auth.ts';
import {coordinate,fail,textField} from './http.ts';
export type Task={id:string;client_id:string;agent_id:string|null;title:string;description:string;location_name:string;target_address:string;target_lat:number;target_lng:number;requirements:string;evidence_requirements:string;status:string;round:number;version:number;mutation_id:string;created_at:string;updated_at:string;started_at:string|null;submitted_at:string|null;completed_at:string|null;client_name?:string;agent_name?:string};
export const states=['REQUESTED','ASSIGNED','ACCEPTED','IN_PROGRESS','SUBMITTED','VERIFIED','COMPLETED'];
const joined='SELECT t.*,c.name client_name,a.name agent_name FROM tasks t JOIN users c ON c.id=t.client_id LEFT JOIN users a ON a.id=t.agent_id';
export async function visibleTask(env:Env,actor:Actor,id:string){const task=await env.DB.prepare(joined+' WHERE t.id=?').bind(id).first<Task>();if(!task||(actor.role==='CLIENT'&&task.client_id!==actor.id)||(actor.role==='AGENT'&&task.agent_id!==actor.id))fail(404,'업무를 찾을 수 없습니다.');return task;}
export async function listTasks(env:Env,actor:Actor,url:URL){const where:string[]=[];const params:(string|number)[]=[];if(actor.role==='CLIENT'){where.push('t.client_id=?');params.push(actor.id);}if(actor.role==='AGENT'){where.push('t.agent_id=?');params.push(actor.id);}const status=url.searchParams.get('status');if(status){if(!states.includes(status))fail(422,'상태가 올바르지 않습니다.');where.push('t.status=?');params.push(status);}const page=Number(url.searchParams.get('page')||0);if(!Number.isSafeInteger(page)||page<0||page>100000)fail(422,'페이지 번호가 올바르지 않습니다.');params.push(50,page*50);return (await env.DB.prepare(joined+(where.length?' WHERE '+where.join(' AND '):'')+' ORDER BY t.created_at DESC LIMIT ? OFFSET ?').bind(...params).all<Task>()).results;}
export function auditStatement(env:Env,actor:Actor,taskId:string,eventId:string,action:string,detail:unknown,now:string){return env.DB.prepare('INSERT INTO audit(id,timestamp,actor_id,actor_role,task_id,action,detail) SELECT ?,?,?,?,?,?,? FROM tasks WHERE id=? AND mutation_id=?').bind(eventId,now,actor.id,actor.role,taskId,action,JSON.stringify(detail),taskId,eventId);}
export async function createTask(env:Env,actor:Actor,body:Record<string,unknown>){
 requireRole(actor,'CLIENT');const fields=[textField(body.title,'제목',160),textField(body.description,'업무 설명'),textField(body.location_name,'수행 위치',200),textField(body.target_address,'주소',500),coordinate(body.target_lat,90),coordinate(body.target_lng,180),textField(body.requirements,'요청사항'),textField(body.evidence_requirements,'Evidence 요구사항')];
 const id='DOIT-'+crypto.randomUUID(),event=crypto.randomUUID(),assignmentEvent=crypto.randomUUID(),now=new Date().toISOString();
 await env.DB.batch([env.DB.prepare('INSERT INTO tasks(id,client_id,title,description,location_name,target_address,target_lat,target_lng,requirements,evidence_requirements,status,mutation_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,\'REQUESTED\',?,?,?)').bind(id,actor.id,...fields,event,now,now),auditStatement(env,actor,id,event,'TASK_CREATED',{},now),
 env.DB.prepare("UPDATE tasks SET agent_id=(SELECT u.id FROM users u LEFT JOIN tasks active ON active.agent_id=u.id AND active.status NOT IN ('COMPLETED') WHERE u.role='AGENT' AND u.auto_assign_enabled=1 GROUP BY u.id ORDER BY count(active.id),u.created_at,u.id LIMIT 1),status='ASSIGNED',mutation_id=?,version=version+1 WHERE id=? AND EXISTS(SELECT 1 FROM users WHERE role='AGENT' AND auto_assign_enabled=1)").bind(assignmentEvent,id),
 env.DB.prepare("INSERT INTO assignments(task_id,agent_id,admin_id,assigned_at) SELECT id,agent_id,NULL,? FROM tasks WHERE id=? AND mutation_id=?").bind(now,id,assignmentEvent),
 env.DB.prepare("INSERT INTO audit(id,timestamp,actor_id,actor_role,task_id,action,detail) SELECT ?,?,client_id,'SYSTEM',id,'AGENT_AUTO_ASSIGNED',json_object('agent_id',agent_id,'from','REQUESTED','to','ASSIGNED') FROM tasks WHERE id=? AND mutation_id=?").bind(assignmentEvent,now,id,assignmentEvent)
 ]);
 return visibleTask(env,actor,id);
}
const transitions:Record<string,{from:string;to:string;role:'ADMIN'|'AGENT'|'CLIENT';event:string}>={accept:{from:'ASSIGNED',to:'ACCEPTED',role:'AGENT',event:'TASK_ACCEPTED'},start:{from:'ACCEPTED',to:'IN_PROGRESS',role:'AGENT',event:'EXECUTION_STARTED'},submit:{from:'IN_PROGRESS',to:'SUBMITTED',role:'AGENT',event:'REPORT_SUBMITTED'},verify:{from:'SUBMITTED',to:'VERIFIED',role:'ADMIN',event:'VERIFICATION_APPROVED'},reexecute:{from:'SUBMITTED',to:'IN_PROGRESS',role:'ADMIN',event:'REEXECUTION_REQUESTED'},complete:{from:'VERIFIED',to:'COMPLETED',role:'CLIENT',event:'TASK_COMPLETED'}};
export async function transition(env:Env,actor:Actor,id:string,action:string,body:Record<string,unknown>){
 const configured=transitions[action];const rule=configured?{...configured}:undefined;if(!rule)fail(404,'지원하지 않는 작업입니다.');requireRole(actor,rule.role);const task=await visibleTask(env,actor,id);if(action==='complete'&&task.status==='SUBMITTED')rule.from='SUBMITTED';if(task.status!==rule.from)fail(409,'현재 상태에서는 실행할 수 없습니다. 새로고침해 주세요.');
 let agent=task.agent_id;const reason=action==='reexecute'?textField(body.reason,'재수행 사유'):'';
 if(action==='assign'){agent=textField(body.agent_id,'Agent',100);const user=await env.DB.prepare("SELECT id FROM users WHERE id=? AND role='AGENT'").bind(agent).first();if(!user)fail(422,'등록된 Agent를 선택해 주세요.');}
 if(action==='submit'){const count=await env.DB.prepare('SELECT count(*) n FROM evidence WHERE task_id=? AND round=? AND removed_at IS NULL').bind(id,task.round).first<{n:number}>();if(!count?.n)fail(409,'현재 수행 회차의 Evidence를 먼저 등록해 주세요.');}
 const now=new Date().toISOString(),event=crypto.randomUUID();const statements=[env.DB.prepare('UPDATE tasks SET status=?,agent_id=?,version=version+1,mutation_id=?,updated_at=?,round=?,started_at=?,submitted_at=?,completed_at=? WHERE id=? AND version=? AND status=?').bind(rule.to,agent,event,now,task.round+(action==='reexecute'?1:0),['start','reexecute'].includes(action)?now:task.started_at,action==='submit'?now:action==='reexecute'?null:task.submitted_at,action==='complete'?now:task.completed_at,id,task.version,rule.from),auditStatement(env,actor,id,event,rule.event,{from:rule.from,to:rule.to,round:task.round,reason,agent_id:agent},now)];
 if(action==='assign')statements.push(env.DB.prepare('INSERT INTO assignments SELECT id,agent_id,?,? FROM tasks WHERE id=? AND mutation_id=?').bind(actor.id,now,id,event));
 if(['verify','reexecute'].includes(action))statements.push(env.DB.prepare('INSERT INTO verifications SELECT ?,id,?,?,?,?,? FROM tasks WHERE id=? AND mutation_id=?').bind(event,task.round,actor.id,action,reason,now,id,event));
 const result=await env.DB.batch(statements);if(result[0].meta.changes!==1)fail(409,'다른 요청이 먼저 처리되었습니다. 새로고침해 주세요.');return visibleTask(env,actor,id);
}
export function distance(lat1:number,lng1:number,lat2:number,lng2:number){const rad=Math.PI/180;const a=Math.sin((lat2-lat1)*rad/2)**2+Math.cos(lat1*rad)*Math.cos(lat2*rad)*Math.sin((lng2-lng1)*rad/2)**2;return Math.round(6371000*2*Math.atan2(Math.sqrt(a),Math.sqrt(Math.max(0,1-a))));}
export async function report(env:Env,actor:Actor,id:string){const task=await visibleTask(env,actor,id);const [evidence,timeline,verifications]=await Promise.all([env.DB.prepare('SELECT e.*,u.name agent_name FROM evidence e JOIN users u ON u.id=e.agent_id WHERE e.task_id=? ORDER BY e.created_at').bind(id).all(),env.DB.prepare("SELECT a.*,CASE WHEN a.actor_role='SYSTEM' THEN '자동 배정' ELSE u.name END actor_name FROM audit a JOIN users u ON u.id=a.actor_id WHERE a.task_id=? ORDER BY a.rowid").bind(id).all(),env.DB.prepare('SELECT * FROM verifications WHERE task_id=? ORDER BY created_at').bind(id).all()]);return {task,evidence:evidence.results.map(e=>({...e,storage_key:undefined,distance_m:e.latitude!=null&&e.longitude!=null?distance(task.target_lat,task.target_lng,Number(e.latitude),Number(e.longitude)):null})),timeline:timeline.results.map(e=>({...e,detail:JSON.parse(String(e.detail))})),verifications:verifications.results};}

