import {readFile,writeFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
const base=process.env.DOIT_URL||'https://doit-r02.namcot.workers.dev';
const users=JSON.parse(await readFile('private/test-accounts.json','utf8'));
const sessions={};const results=[];let taskId;
async function step(name,fn){try{await fn();results.push({name,status:'PASS'});console.log('PASS',name)}catch(e){results.push({name,status:'FAIL',detail:e.message});throw e;}}
async function req(path,actor,body,extra={}){const s=sessions[actor];const user=users.find(u=>u.email.startsWith(actor+'@'));const headers={...(s?{cookie:s.cookie,'x-csrf-token':s.csrf,'x-doit-role':user.role}:{}),...(body===undefined?{}:{origin:base}),...(body instanceof FormData?{}:{'content-type':'application/json'}),...extra};return fetch(base+'/api'+path,{method:body===undefined?'GET':'POST',headers,...(body===undefined?{}:{body:body instanceof FormData?body:JSON.stringify(body)})});}
async function expect(r,status){assert.equal(r.status,status,(await r.clone().text()).slice(0,350));return r;}
try{
 await step('HTTPS CORE DB STORAGE health',async()=>{const r=await expect(await fetch(base+'/api/health'),200);assert.equal((await r.json()).ready,true)});
 for(const actor of ['client','agent','admin','otherclient','otheragent'])await step(actor+' login',async()=>{const u=users.find(u=>u.email.startsWith(actor+'@'));const r=await expect(await req('/auth/login',actor,{email:u.email,password:u.password}),200);const data=await r.json();sessions[actor]={csrf:data.csrf,cookie:r.headers.get('set-cookie').split(';')[0]};assert.equal(data.user.role,u.role)});
 await step('Client creates Task',async()=>{const r=await expect(await req('/tasks','client',{title:'[실환경 검증] 현장 사진·영상 확인 '+new Date().toISOString().slice(0,16),description:'Cloudflare D1·R2에서 1:1 전체 실행 흐름을 검증합니다. 실제 현장 촬영이 아닌 자동 테스트 자료입니다.',location_name:'서울 시청 · 테스트 좌표',target_address:'서울 중구 세종대로 110',target_lat:37.5665,target_lng:126.978,requirements:'자동 검증 샘플',evidence_requirements:'사진, 영상, GPS, 현장 메모'}),201);taskId=(await r.json()).id;});
 await step('Other Client and unassigned Agent denied',async()=>{await expect(await req('/tasks/'+taskId,'otherclient'),404);await expect(await req('/tasks/'+taskId,'otheragent'),404)});
 await step('Server prevents skipped status',async()=>{await expect(await req('/tasks/'+taskId+'/verify','admin',{}),409)});
 await step('Admin assigns Agent',async()=>{await expect(await req('/tasks/'+taskId+'/assign','admin',{agent_id:users.find(u=>u.email==='agent@doit.test').id}),200)});
 for(const action of ['accept','start'])await step('Agent '+action,async()=>{await expect(await req('/tasks/'+taskId+'/'+action,'agent',{}),200)});
 const media=[{filename:'sample.png',type:'image/png',bytes:await readFile('tests/fixtures/sample.png')}];
 try{media.push({filename:'sample.webm',type:'video/webm',bytes:await readFile('tests/fixtures/sample.webm')})}catch{results.push({name:'Video upload',status:'NOT_RUN',detail:'실제 WEBM fixture 준비 전'});}
 for(const m of media){let id;const form=()=>{const f=new FormData();f.append('file',new Blob([m.bytes],{type:m.type}),m.filename);f.append('latitude','37.5665');f.append('longitude','126.978');f.append('accuracy','10');f.append('note','자동 테스트용 Evidence · 실제 현장 자료 아님');return f;};await step(m.filename+' upload, Task link and SHA256',async()=>{await expect(await req('/tasks/'+taskId+'/evidence','otheragent',form()),404);const r=await expect(await req('/tasks/'+taskId+'/evidence','agent',form()),201);const e=await r.json();id=e.id;assert.equal(e.task_id,taskId);assert.equal(e.sha256,createHash('sha256').update(m.bytes).digest('hex'))});await step(m.filename+' authorized content, Range and access denial',async()=>{const r=await expect(await req('/evidence/'+id+'/content','client'),200);assert.deepEqual(Buffer.from(await r.arrayBuffer()),m.bytes);await expect(await req('/evidence/'+id+'/content','otherclient'),404);const range=await expect(await req('/evidence/'+id+'/content','admin',undefined,{range:'bytes=0-7'}),206);assert.equal((await range.arrayBuffer()).byteLength,8)});}
 await step('Agent cannot directly verify',async()=>await expect(await req('/tasks/'+taskId+'/verify','agent',{}),403));
 for(const [action,actor] of [['submit','agent'],['verify','admin'],['complete','admin']])await step(actor+' '+action,async()=>await expect(await req('/tasks/'+taskId+'/'+action,actor,{}),200));
 await step('Client report and complete audit',async()=>{const d=await(await expect(await req('/tasks/'+taskId+'/report','client'),200)).json();assert.equal(d.task.status,'COMPLETED');assert.equal(d.evidence.length,media.length);assert.equal(d.timeline.at(-1).action,'TASK_COMPLETED');assert.equal(d.evidence[0].distance_m,0)});
}catch(e){console.error('LIVE TEST FAILED:',e.message);process.exitCode=1;}finally{await mkdir('test-results',{recursive:true});await writeFile('test-results/live-results.json',JSON.stringify({base,at:new Date().toISOString(),taskId,results},null,2));console.log('Result file: test-results/live-results.json');}
