import {chromium,expect} from '@playwright/test';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
const base='https://doit-r02.namcot.workers.dev';
const accounts=JSON.parse(await readFile('private/test-accounts.json','utf8'));
const browser=await chromium.launch({channel:'msedge',headless:true});const errors=[],results=[];
const contexts=[];
async function pageFor(role,mobile=false){const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000},isMobile:mobile,hasTouch:mobile,permissions:['geolocation'],geolocation:{latitude:37.5665,longitude:126.978,accuracy:10}});contexts.push(context);const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));const u=accounts.find(a=>a.role===role);await page.goto(base+'/'+role.toLowerCase());await page.getByLabel('이메일').fill(u.email);await page.getByLabel('비밀번호').fill(u.password);await page.getByRole('button',{name:'워크스페이스 시작하기'}).click();await page.getByRole('heading',{name:'업무 목록'}).waitFor();await expect(page.getByRole('button',{name:'새로고침'})).toBeEnabled();return page;}
async function step(name,fn){try{await fn();results.push({name,status:'PASS'});console.log('PASS',name)}catch(e){results.push({name,status:'FAIL',detail:e.message});throw e;}}
const title='[브라우저 E2E] 현장 확인 '+Date.now();
try{
 const client=await pageFor('CLIENT');
 await step('Client creates task with interactive destination map',async()=>{await client.getByRole('button',{name:'새 업무 의뢰'}).click();await client.getByLabel('업무 제목').fill(title);await client.getByLabel('업무 설명',{exact:true}).fill('브라우저 테스트용 자료입니다. 실제 현장 기록이 아닙니다.');await client.getByLabel('수행 위치',{exact:true}).fill('서울 시청');await client.getByLabel('주소',{exact:true}).fill('서울 중구 세종대로 110');await client.getByLabel('목적지 위도').fill('37.5665');await client.getByLabel('목적지 경도').fill('126.978');await client.getByLabel('요청사항',{exact:true}).fill('입구 확인');await client.getByLabel('필요 사진·동영상').fill('사진 및 영상');await expect(client.getByTestId('location-map')).toBeVisible();await client.getByRole('button',{name:'의뢰 등록'}).click();await client.getByRole('heading',{name:title,exact:true}).waitFor();});
 const admin=await pageFor('ADMIN');
 await step('Admin assigns Agent through UI',async()=>{await admin.getByRole('button',{name:title,exact:true}).click();await admin.getByLabel('배정할 Agent').selectOption(accounts.find(x=>x.email==='agent@doit.test').id);await admin.getByRole('button',{name:'Agent 배정',exact:true}).click();await expect(admin.locator('.detail-head .badge')).toHaveText('배정 완료');});
 const agent=await pageFor('AGENT',true);
 await step('Mobile Agent accepts and starts',async()=>{await agent.getByRole('button',{name:title,exact:true}).click();await agent.getByRole('button',{name:'의뢰 수락',exact:true}).click();await agent.getByRole('button',{name:'업무 시작',exact:true}).click();await expect(agent.getByRole('heading',{name:'현장 기록 등록'})).toBeVisible();});
 await step('GPS plus image and real video upload',async()=>{await agent.getByRole('button',{name:'현재 GPS 기록'}).click();await expect(agent.getByText(/GPS 기록 완료/)).toBeVisible();await agent.getByLabel('현장 메모').fill('브라우저 자동 검증: 현장 촬영 아님');await agent.getByLabel('사진 또는 동영상').setInputFiles({name:'browser.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a3ioAAAAASUVORK5CYII=','base64')});await agent.getByRole('button',{name:'Evidence 등록',exact:true}).click();await expect(agent.locator('.gallery article')).toHaveCount(1);await agent.getByLabel('사진 또는 동영상').setInputFiles('tests/fixtures/sample.webm');await agent.getByRole('button',{name:'Evidence 등록',exact:true}).click();await expect(agent.locator('.gallery article')).toHaveCount(2);await agent.getByRole('button',{name:'수행 완료 / 보고 제출'}).click();await expect(agent.locator('.detail-head .badge')).toHaveText('검증 대기');});
 await step('Admin reviews video then verifies and completes',async()=>{await admin.getByRole('button',{name:'업무 목록',exact:true}).click();await admin.getByRole('button',{name:'새로고침'}).click();await admin.getByRole('button',{name:title,exact:true}).click();const video=admin.locator('video');await video.evaluate(async v=>{await v.play();await new Promise((resolve,reject)=>{if(v.readyState>=3)return resolve();v.addEventListener('canplay',resolve,{once:true});v.addEventListener('error',reject,{once:true});});v.pause()});await admin.getByRole('button',{name:'검증 승인',exact:true}).click();await admin.getByRole('button',{name:'완료 처리',exact:true}).click();await expect(admin.locator('.detail-head .badge')).toHaveText('완료');});
 await step('Client report with evidence and audit visible',async()=>{await client.getByRole('button',{name:'업무 목록',exact:true}).click();await client.getByRole('button',{name:'새로고침'}).click();await client.getByRole('button',{name:title,exact:true}).click();await expect(client.locator('.detail-head .badge')).toHaveText('완료');await expect(client.locator('.gallery article')).toHaveCount(2);await expect(client.locator('.timeline')).toContainText('완료 처리');await client.screenshot({path:'test-results/report-desktop.png',fullPage:true});await agent.screenshot({path:'test-results/execution-mobile.png',fullPage:true});});
 if(errors.length)throw new Error(errors.join('\n'));
}catch(e){console.error(e.message);process.exitCode=1;}finally{await mkdir('test-results',{recursive:true});await writeFile('test-results/ui-results.json',JSON.stringify({at:new Date().toISOString(),title,results,errors},null,2));await browser.close();}
