import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {api,role,setCSRF,type User} from './api';
import type {Task} from '../core/tasks';
import './style.css';
import {LocationMap} from './LocationMap';
import {TaskForm} from './TaskForm';
import {collectLocation,type LocationReading} from './gps';

const roleName:Record<string,string>={CLIENT:'의뢰인',AGENT:'에이전트',ADMIN:'관리자'};
const statusName:Record<string,string>={REQUESTED:'배정 대기',ASSIGNED:'배정 완료',ACCEPTED:'수락 완료',IN_PROGRESS:'수행 중',SUBMITTED:'검증 대기',VERIFIED:'검증 완료',COMPLETED:'완료'};
const actionName:Record<string,string>={TASK_CREATED:'의뢰 등록',AGENT_ASSIGNED:'Agent 배정',TASK_ACCEPTED:'의뢰 수락',EXECUTION_STARTED:'현장 업무 시작',EVIDENCE_UPLOADED:'Evidence 등록',REPORT_SUBMITTED:'수행 보고 제출',VERIFICATION_APPROVED:'검증 승인',REEXECUTION_REQUESTED:'재수행 요청',TASK_COMPLETED:'완료 처리',EVIDENCE_REMOVED:'Evidence 제외'};
type Evidence={id:string;filename:string;mime:string;size:number;sha256:string;latitude:number|null;longitude:number|null;accuracy:number|null;created_at:string;captured_at:string|null;location_recorded_at:string|null;agent_name:string;note:string;round:number;distance_m:number|null;removed_at:string|null};
type Report={task:Task;evidence:Evidence[];timeline:{id:string;action:string;timestamp:string;actor_name:string;detail:{reason?:string}}[];verifications:{id:string;round:number;result:string;reason:string;created_at:string}[]};
const date=(value:string|null)=>value?new Date(value).toLocaleString('ko-KR'):'—';
function Badge({status}:{status:string}){return <span className={'badge '+status}>{statusName[status]||status}</span>}
function App(){
 const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tasks,setTasks]=useState<Task[]>([]),[selected,setSelected]=useState<Report|null>(null),[creating,setCreating]=useState(false),[filter,setFilter]=useState(''),[page,setPage]=useState(0),[busy,setBusy]=useState(false),[health,setHealth]=useState<Record<string,unknown>>({});
 async function refresh(){setTasks(await api<Task[]>('/tasks?status='+filter+'&page='+page));}
 async function open(id:string){setCreating(false);setSelected(await api<Report>('/tasks/'+id));}
 async function run(job:()=>Promise<void>){setError('');setBusy(true);try{await job()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{api<{user:User;csrf:string}>('/auth/me').then(d=>{setUser(d.user);setCSRF(d.csrf)}).catch(()=>{}).finally(()=>setLoading(false));fetch('/api/health').then(r=>r.json()).then(d=>setHealth(d as Record<string,unknown>)).catch(()=>setHealth({core:false}));},[]);
 useEffect(()=>{if(user)void run(refresh)},[user,filter,page]);
 useEffect(()=>{if(!user||busy)return;let alive=true;const timer=setInterval(async()=>{if(document.visibilityState!=='visible')return;try{const rows=await api<Task[]>('/tasks?status='+filter+'&page='+page);if(alive)setTasks(rows);if(selected){const detail=await api<Report>('/tasks/'+selected.task.id);if(alive)setSelected(detail);}}catch{}},15000);return()=>{alive=false;clearInterval(timer)}},[user?.id,busy,filter,page,selected?.task.id]);
 async function action(action:string,body:unknown={}){if(!selected)return;await api('/tasks/'+selected.task.id+'/'+action,body);await open(selected.task.id);await refresh();}
 return <div className="shell"><aside><a className="brand" href="/">DOIT<span>●</span></a><div className="version">EXECUTION PLATFORM · R0.2</div><div className="space-label">WORKSPACE</div><nav>{Object.entries(roleName).map(([r,name])=><a className={role===r?'active':''} href={'/'+r.toLowerCase()} key={r}><span>{r==='CLIENT'?'↗':r==='AGENT'?'◎':'▦'}</span>{name} APP{role===r&&<i/>}</a>)}</nav><div className="sidebar-note"><span className="live-dot"/> Cloud workspace<br/><small>의뢰부터 현장 증빙까지<br/>하나의 업무 흐름으로.</small></div></aside><div className="workspace"><header><span>WORKSPACE <b>/</b> {roleName[role]} APP</span><div className="identity">{user?<><span className="avatar">{user.name[0]}</span>{user.name}<button className="text-button" onClick={()=>void run(async()=>{await api('/auth/logout',{});setUser(null);setSelected(null);setTasks([])})}>로그아웃</button></>:<span>현장과 연결되는 업무</span>}</div></header><main>
 {error&&<div role="alert" className="error">{error}<button onClick={()=>setError('')}>닫기</button></div>}
 {loading?<div className="empty">워크스페이스를 불러오는 중입니다.</div>:!user?<Login onLogin={(u,c)=>{setUser(u);setCSRF(c)}} onError={setError}/>:<>
 <div className="page-title"><div><div className="eyebrow">{role} WORKSPACE</div><h1>{role==='CLIENT'?'현장 업무를 한눈에':role==='AGENT'?'오늘의 현장 업무':'실행 현황 관리'}</h1><p>{role==='CLIENT'?'의뢰하고, 진행을 확인하고, 현장의 결과를 만나세요.':role==='AGENT'?'배정된 업무를 확인하고 현장의 기록을 전달하세요.':'배정부터 Evidence 검증까지, 모든 실행을 관리하세요.'}</p></div>{role==='CLIENT'&&<button className="primary" onClick={()=>{setCreating(true);setSelected(null)}}>＋ 새 업무 의뢰</button>}</div>
 <div className="stats">{[['조회된 업무',tasks.length,'현재 페이지'],['수행 중',tasks.filter(t=>['ASSIGNED','ACCEPTED','IN_PROGRESS'].includes(t.status)).length,'현장으로 연결된 업무'],['검증 대기',tasks.filter(t=>t.status==='SUBMITTED').length,'보고가 도착한 업무'],['완료',tasks.filter(t=>t.status==='COMPLETED').length,'확인된 결과']].map(([label,n,hint])=><div key={label}><span>{label}</span><strong>{n}<small>건</small></strong><p>{hint}</p></div>)}</div>
 {creating?<TaskForm busy={busy} submit={body=>run(async()=>{const t=await api<Task>('/tasks',body);await refresh();await open(t.id)})} cancel={()=>setCreating(false)}/>:selected?<Detail report={selected} busy={busy} back={()=>setSelected(null)} execute={(a,b)=>run(()=>action(a,b))} upload={body=>run(async()=>{await api('/tasks/'+selected.task.id+'/evidence',body);await open(selected.task.id);await refresh()})}/>:<section className="panel"><div className="panel-title"><h2>업무 목록 <small>{tasks.length}</small></h2><button className="text-button" disabled={busy} onClick={()=>void run(refresh)}>↻ 새로고침</button></div><div className="filters"><button className={!filter?'selected':''} onClick={()=>{setFilter('');setPage(0)}}>전체</button>{Object.entries(statusName).map(([s,label])=><button key={s} className={filter===s?'selected':''} onClick={()=>{setFilter(s);setPage(0)}}>{label}</button>)}</div><div className="table-scroll"><table><thead><tr><th>업무 / Task ID</th><th>수행 위치</th><th>담당 Agent</th><th>상태</th><th>최근 업데이트</th><th/></tr></thead><tbody>{tasks.map(t=><tr key={t.id}><td><button className="task-link" onClick={()=>void run(()=>open(t.id))}>{t.title}</button><small title={t.id}>{t.id.slice(0,18)}…</small></td><td>{t.location_name}<small>{t.target_address}</small></td><td>{t.agent_name||'미배정'}</td><td><Badge status={t.status}/></td><td>{date(t.updated_at)}</td><td><button className="text-button" aria-label={t.title+' 상세'} onClick={()=>void run(()=>open(t.id))}>↗</button></td></tr>)}</tbody></table></div>{!tasks.length&&<div className="empty"><div className="empty-icon">▤</div><h3>아직 표시할 업무가 없습니다</h3><p>{role==='CLIENT'?'새 업무를 의뢰해 첫 실행을 시작하세요.':'배정 또는 상태 변경 후 새로고침해 주세요.'}</p></div>}<div className="pagination"><button disabled={!page||busy} onClick={()=>setPage(p=>p-1)}>이전</button><span>{page+1} 페이지</span><button disabled={tasks.length<50||busy} onClick={()=>setPage(p=>p+1)}>다음</button></div></section>}
 </>}
 <footer><span>DOIT · 1:1 Execution</span><div>{[['CORE',health.core],['DB',health.db],['API',health.api],['STORAGE',health.storage]].map(([label,ok])=><span key={String(label)}><i className={ok?'ok':'off'}/>{String(label)}</span>)}<span><i className="fallback"/>GEO · {String(health.geo||'확인 중')}</span></div></footer>
 </main></div></div>
}
function Login({onLogin,onError}:{onLogin:(u:User,c:string)=>void;onError:(e:string)=>void}){const[busy,setBusy]=useState(false);return <section className="login"><div className="eyebrow">REAL WORK. VERIFIED.</div><h1>현장과 연결되는<br/>가장 확실한 방법.</h1><p>의뢰, 수행, 증빙, 검증.<br/>DOIT에서 하나의 흐름으로 이어집니다.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);onError('');const f=new FormData(e.currentTarget);try{const d=await api<{user:User;csrf:string}>('/auth/login',{email:f.get('email'),password:f.get('password')});if(d.user.role!==role){location.href='/'+d.user.role.toLowerCase();return}onLogin(d.user,d.csrf)}catch(error){onError((error as Error).message)}finally{setBusy(false)}}}><h2>{roleName[role]} 로그인</h2><label>이메일<input name="email" type="email" required autoComplete="username" placeholder="이메일을 입력하세요"/></label><label>비밀번호<input name="password" type="password" required autoComplete="current-password" placeholder="비밀번호를 입력하세요"/></label><button className="primary" disabled={busy}>{busy?'확인 중…':'워크스페이스 시작하기 →'}</button><small>초대받은 테스트 계정으로 로그인하세요.</small></form></section>}
function Detail({report:r,busy,back,execute,upload}:{report:Report;busy:boolean;back:()=>void;execute:(a:string,b?:unknown)=>Promise<void>;upload:(body:FormData)=>Promise<void>}){const[agents,setAgents]=useState<User[]>([]),[agent,setAgent]=useState(''),[reason,setReason]=useState('');const t=r.task;useEffect(()=>{if(role==='ADMIN')api<User[]>('/agents').then(setAgents).catch(()=>{})},[]);return <><button className="back" onClick={back}>← 업무 목록</button><section className="panel detail-head"><div><div className="eyebrow">EXECUTION REPORT · ROUND {t.round}</div><h2>{t.title}</h2><p className="id">{t.id}</p></div><Badge status={t.status}/></section><div className="detail-grid"><div><section className="panel content"><h2>의뢰 내용</h2><p className="pre">{t.description}</p><dl><dt>의뢰인</dt><dd>{t.client_name}</dd><dt>담당 Agent</dt><dd>{t.agent_name||'배정 대기'}</dd><dt>수행 위치</dt><dd>{t.location_name}<br/>{t.target_address}<small>{t.target_lat}, {t.target_lng}</small></dd><dt>생성일</dt><dd>{date(t.created_at)}</dd><dt>업무 시작</dt><dd>{date(t.started_at)}</dd><dt>보고 제출</dt><dd>{date(t.submitted_at)}</dd><dt>요청사항</dt><dd className="pre">{t.requirements}</dd><dt>필요 Evidence</dt><dd className="pre">{t.evidence_requirements}</dd></dl><LocationMap lat={t.target_lat} lng={t.target_lng} points={r.evidence.filter(e=>e.latitude!==null&&e.longitude!==null).map(e=>({lat:e.latitude!,lng:e.longitude!,label:e.filename}))}/><a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${t.target_lat},${t.target_lng}`}>목적지 지도 보기 ↗</a></section>
 <section className="panel content"><div className="panel-title"><h2>현장 Evidence <small>{r.evidence.length}</small></h2><span className="eyebrow">ORIGINAL FILES</span></div>{!r.evidence.length?<p className="muted">아직 등록된 사진·동영상이 없습니다.</p>:<div className="gallery">{r.evidence.map(e=>{const src='/api/evidence/'+e.id+'/content?app='+role;return <article className={e.removed_at?'removed':''} key={e.id}>{e.mime.startsWith('image/')?<a href={src} target="_blank" rel="noreferrer"><img loading="lazy" src={src} alt={e.note||e.filename}/></a>:<video src={src} controls preload="metadata" playsInline/>}<div><strong>{e.filename}</strong><span className="pill">회차 {e.round}{e.removed_at?' · 제외됨':''}</span><p className="pre">{e.note||'메모 없음'}</p><small>{e.agent_name} · {date(e.created_at)}<br/>{e.mime} · {(e.size/1024/1024).toFixed(2)} MB<br/>GPS {e.latitude===null?'미기록':`${e.latitude}, ${e.longitude}`}<br/>목적지 거리 {e.distance_m===null?'계산 불가':e.distance_m+' m'}</small><details><summary>Evidence 정보</summary><small className="hash">{e.id}<br/>촬영 시각: {date(e.captured_at)}<br/>GPS 수집: {date(e.location_recorded_at)}<br/>SHA-256: {e.sha256}</small></details></div></article>})}</div>}</section>
 {role==='AGENT'&&t.status==='IN_PROGRESS'&&<EvidenceForm key={t.id} busy={busy} upload={upload}/>}
 {r.verifications.length>0&&<section className="panel content"><h2>검증 기록</h2>{r.verifications.map(v=><p key={v.id}><b>{v.round}회차 · {v.result==='verify'?'승인':'재수행 요청'}</b><br/>{v.reason}<small>{date(v.created_at)}</small></p>)}</section>}</div><div><section className="panel content actions"><h2>다음 단계</h2>{role==='ADMIN'&&t.status==='REQUESTED'&&<><label>배정할 Agent<select value={agent} onChange={e=>setAgent(e.target.value)}><option value="">Agent 선택</option>{agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><button className="primary" disabled={busy||!agent} onClick={()=>void execute('assign',{agent_id:agent})}>Agent 배정</button></>}{role==='AGENT'&&['ASSIGNED','ACCEPTED','IN_PROGRESS'].includes(t.status)&&<button className="primary" disabled={busy} onClick={()=>void execute(t.status==='ASSIGNED'?'accept':t.status==='ACCEPTED'?'start':'submit')}>{t.status==='ASSIGNED'?'의뢰 수락':t.status==='ACCEPTED'?'업무 시작':'수행 완료 / 보고 제출'}</button>}{role==='ADMIN'&&t.status==='SUBMITTED'&&<><button className="primary" disabled={busy} onClick={()=>void execute('verify')}>검증 승인</button><label>재수행 사유<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!reason.trim()} onClick={()=>void execute('reexecute',{reason})}>재수행 요청</button></>}{role==='ADMIN'&&t.status==='VERIFIED'&&<button className="primary" disabled={busy} onClick={()=>void execute('complete')}>완료 처리</button>}{role==='CLIENT'&&<p className="muted">진행 상황과 제출된 결과를 확인할 수 있습니다.</p>}{role==='AGENT'&&t.status==='SUBMITTED'&&<p className="muted">관리자 검증을 기다리고 있습니다.</p>}{role==='AGENT'&&t.status==='VERIFIED'&&<p className="muted">검증이 승인되었습니다. 완료 처리를 기다리고 있습니다.</p>}{t.status==='COMPLETED'&&<div className="complete">✓ 업무가 완료되었습니다</div>}</section><section className="panel content"><h2>Execution Timeline</h2><ol className="timeline">{r.timeline.map(event=><li key={event.id}><strong>{actionName[event.action]||event.action}</strong><small>{event.actor_name} · {date(event.timestamp)}</small>{event.detail.reason&&<p>{event.detail.reason}</p>}</li>)}</ol></section></div></div></>}
function EvidenceForm({busy,upload}:{busy:boolean;upload:(f:FormData)=>Promise<void>}){const[gps,setGPS]=useState<LocationReading|null>(null),[message,setMessage]=useState(''),[locating,setLocating]=useState(false);async function locate(){setMessage('현재 위치를 확인하는 중…');setLocating(true);try{const p=await collectLocation(setGPS,navigator.geolocation);setMessage('GPS 기록 완료 · 정확도 ±'+Math.round(p.accuracy)+' m · '+date(p.location_recorded_at))}catch(e){setMessage((e as Error).message)}finally{setLocating(false)}}return <section className="panel content"><h2>현장 기록 등록</h2><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(gps)Object.entries(gps).forEach(([k,v])=>f.set(k,String(v)));void upload(f)}}><label>사진 또는 동영상<input name="file" type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" capture="environment" required/></label><p className="hint">JPG · PNG · WEBP · MP4 · WEBM / 파일당 최대 25 MB. 여러 파일은 한 번씩 등록하세요.</p><button type="button" disabled={locating||busy} onClick={()=>void locate()}>◎ 현재 GPS 기록</button><p className="hint">{message||'현장 위치를 함께 기록해 주세요.'}</p><label>현장 메모<textarea name="note" placeholder="현장에서 확인한 내용을 작성하세요."/></label><button className="primary" disabled={busy}>{busy?'업로드 중…':'Evidence 등록'}</button></form></section>}
createRoot(document.getElementById('root')!).render(<App/>);
