const japanese:Record<string,string>={
 '의뢰인':'依頼者','에이전트':'エージェント','관리자':'管理者','배정 대기':'割り当て待ち','배정 완료':'割り当て済み','수락 완료':'受諾済み','수행 중':'作業中','보고 제출':'報告提出','검증 완료':'確認済み','완료':'完了',
 '의뢰 등록':'依頼登録','Agent 배정':'担当者の割り当て','Agent 자동 배정':'担当者の自動割り当て','의뢰 수락':'依頼を受諾','현장 업무 시작':'現地作業開始','Evidence 등록':'証拠を登録','수행 보고 제출':'作業報告提出','검증 승인':'確認承認','재수행 요청':'再作業依頼','완료 처리':'完了処理','Evidence 제외':'証拠を除外',
 '의뢰부터 현장 증빙까지':'依頼から現地の証拠まで','하나의 업무 흐름으로.':'一つのワークフローで。','로그아웃':'ログアウト','현장과 연결되는 업무':'現地とつながる仕事','닫기':'閉じる','워크스페이스를 불러오는 중입니다.':'ワークスペースを読み込み中です。',
 '현장 업무를 한눈에':'現地作業を一覧で確認','오늘의 현장 업무':'現地作業一覧','실행 현황 관리':'作業状況の管理','의뢰하고, 진행을 확인하고, 현장의 결과를 만나세요.':'依頼し、進捗を確認し、現地の結果を受け取れます。','배정된 업무를 확인하고 현장의 기록을 전달하세요.':'担当業務を確認し、現地の記録を提出してください。','배정부터 Evidence 검증까지, 모든 실행을 관리하세요.':'担当者の割り当てから証拠の確認まで管理します。','＋ 새 업무 의뢰':'＋ 新しい依頼',
 '조회된 업무':'表示中の業務','현재 페이지':'現在のページ','현장으로 연결된 업무':'進行中の現地作業','검증 대기':'確認待ち','보고가 도착한 업무':'報告済みの業務','확인된 결과':'確認済みの結果','건':'件','업무 목록':'業務一覧','↻ 새로고침':'↻ 更新','전체':'すべて','업무 / Task ID':'業務 / Task ID','수행 위치':'作業場所','담당 Agent':'担当者','상태':'状態','최근 업데이트':'最終更新','미배정':'未割り当て','상세':'詳細','아직 표시할 업무가 없습니다':'表示できる業務はありません','새 업무를 의뢰해 첫 실행을 시작하세요.':'新しい業務を依頼してください。','배정 또는 상태 변경 후 새로고침해 주세요.':'割り当てや状態変更後に更新してください。','이전':'前へ','페이지':'ページ','다음':'次へ','확인 중':'確認中',
 '현장과 연결되는':'現地とつながる','가장 확실한 방법.':'確かな方法。','의뢰, 수행, 증빙, 검증.':'依頼、作業、証拠、確認。','DOIT에서 하나의 흐름으로 이어집니다.':'DOITで一つの流れにつながります。','로그인':'ログイン','이메일':'メールアドレス','이메일을 입력하세요':'メールアドレスを入力','비밀번호':'パスワード','비밀번호를 입력하세요':'パスワードを入力','확인 중…':'確認中…','워크스페이스 시작하기 →':'ワークスペースを開く →','초대받은 테스트 계정으로 로그인하세요.':'招待されたテストアカウントでログインしてください。',
 '← 업무 목록':'← 業務一覧','의뢰 내용':'依頼内容','생성일':'作成日時','업무 시작':'作業開始','요청사항':'依頼事項','필요 Evidence':'必要な証拠','목적지 지도 보기 ↗':'目的地を地図で見る ↗','현장 Evidence':'現地の証拠','아직 등록된 사진·동영상이 없습니다.':'写真・動画はまだ登録されていません。','회차':'回','· 제외됨':'· 除外済み','메모 없음':'メモなし','미기록':'未記録','목적지 거리':'目的地までの距離','계산 불가':'計算不可','Evidence 정보':'証拠の情報','촬영 시각:':'撮影日時:','GPS 수집:':'GPS取得日時:','검증 기록':'確認履歴','회차 ·':'回 ·','승인':'承認','다음 단계':'次のステップ','자동 배정 가능한 Agent를 기다리고 있습니다.':'担当可能なエージェントを待っています。','수행 완료 / 보고 제출':'作業完了 / 報告を提出','재수행 사유':'再作業の理由','결과 확인 / 완료':'結果を確認 / 完了','진행 상황과 제출된 결과를 확인할 수 있습니다.':'進捗と提出された結果を確認できます。','클라이언트에게 보고가 전달되었습니다. 결과 확인을 기다리고 있습니다.':'依頼者に報告を送信しました。結果の確認待ちです。','검토가 완료되었습니다. 클라이언트의 결과 확인을 기다리고 있습니다.':'レビューが完了しました。依頼者の確認待ちです。','✓ 업무가 완료되었습니다':'✓ 業務が完了しました',
 '현재 위치를 확인하는 중…':'現在地を確認中…','GPS 기록 완료 · 정확도 ±':'GPS記録完了 · 精度 ±','현장 기록 등록':'現地記録の登録','사진 또는 동영상':'写真または動画','JPG · PNG · WEBP · MP4 · WEBM / 파일당 최대 25 MB. 여러 파일은 한 번씩 등록하세요.':'JPG · PNG · WEBP · MP4 · WEBM / 1ファイル最大25 MB。複数のファイルは1つずつ登録してください。','◎ 현재 GPS 기록':'◎ 現在地のGPSを記録','현장 위치를 함께 기록해 주세요.':'現地の位置情報も記録してください。','현장 메모':'現地メモ','현장에서 확인한 내용을 작성하세요.':'現地で確認した内容を入力してください。','업로드 중…':'アップロード中…',
 '입력 내용이 바뀌어 이전 AI 결과를 적용하지 않았습니다.':'入力が変更されたため、以前のAI結果は適用されませんでした。','결과 언어':'出力言語','한국어':'한국어','AI 번역':'AI翻訳','AI 내용 정리':'AIで内容を整理','버튼을 누르면 이 텍스트만 Gemini에 전송됩니다. 사진·영상은 전송하지 않습니다. 4,000자 이내.':'ボタンを押すと、このテキストのみをGeminiに送信します。写真・動画は送信しません。4,000文字以内。','AI가 텍스트를 처리하고 있습니다…':'AIがテキストを処理中です…','번역':'翻訳','내용 정리':'内容整理','· 요청 언어:':'· 指定言語:','사실과 번역을 확인해 주세요.':'事実と翻訳を確認してください。','확인 후 적용':'確認して適用','요청 원문':'原文','적용 전 원문 복원':'適用前の原文に戻す',
 '번역 언어':'翻訳言語','전체 번역 중…':'全体を翻訳中…','번역 표시 중':'翻訳を表示中','의뢰 전체 번역 / 一括翻訳':'依頼を一括翻訳','원문 보기 / 原文':'原文を表示','제목·내용·요청사항·필요 증빙·수행 위치·주소를 함께 번역합니다. 원문은 보존됩니다. 항목별 AI 사용 한도가 적용됩니다.':'件名・内容・依頼事項・必要な証拠・作業場所・住所を翻訳します。原文は保存されます。AI利用上限は項目ごとに適用されます。','AI 번역 ·':'AI翻訳 ·','· 주소와 고유명사는 원문도 확인해 주세요.':'· 住所や固有名詞は原文も確認してください。','전체 번역을 적용하지 않았습니다.':'全体翻訳を適用できませんでした。',
 '목적지':'目的地','목적지와 Evidence 위치 지도':'目的地と証拠の位置を示す地図','지도 연결에 실패해 OpenStreetMap으로 표시합니다. 좌표 입력은 계속 사용할 수 있습니다.':'地図に接続できないためOpenStreetMapを表示します。座標入力は引き続き利用できます。','MapTiler 지도':'MapTiler地図','VWorld 지도':'VWorld地図','OpenStreetMap 대체 지도':'OpenStreetMap地図','지도 연결 중':'地図に接続中','지도를 클릭하여 목적지를 선택하세요.':'地図をクリックして目的地を選択してください。','초록: 목적지 · 주황: Evidence 위치':'緑：目的地 · オレンジ：証拠の位置','지도를 준비하고 있습니다…':'地図を準備中です…','이 브라우저에서 위치 기능을 사용할 수 없습니다.':'このブラウザでは位置情報を利用できません。','위치 권한과 HTTPS 연결을 확인해 주세요. 이전 위치는 삭제되었습니다.':'位置情報の許可とHTTPS接続を確認してください。以前の位置情報は削除されました。',
 '요청을 처리하지 못했습니다.':'リクエストを処理できませんでした。','AI 처리에 실패했습니다. 원문은 유지되며 자동 재시도하지 않습니다.':'AI処理に失敗しました。原文を保持し、自動再試行は行いません。','오늘 AI 사용 한도에 도달했습니다. 원문으로 계속 작성할 수 있습니다.':'本日のAI利用上限に達しました。原文で作業を続けられます。','AI 연결 준비 중입니다. Vertex AI 인증 설정 후 사용할 수 있습니다.':'AI接続の準備中です。認証設定後に利用できます。',
 'Execution Timeline':'作業履歴','ORIGINAL FILES':'原本ファイル','Cloud workspace':'クラウドワークスペース','WORKSPACE':'ワークスペース'
};
const english:Record<string,string>={
 '의뢰인':'Client','에이전트':'Agent','관리자':'Admin','배정 대기':'Awaiting assignment','배정 완료':'Assigned','수락 완료':'Accepted','수행 중':'In progress','보고 제출':'Report submitted','검증 완료':'Verified','완료':'Completed','의뢰 등록':'Request created','Agent 배정':'Agent assigned','Agent 자동 배정':'Agent automatically assigned','의뢰 수락':'Accept request','현장 업무 시작':'Field work started','Evidence 등록':'Upload evidence','수행 보고 제출':'Report submitted','검증 승인':'Approve verification','재수행 요청':'Request rework','완료 처리':'Marked complete','Evidence 제외':'Evidence excluded',
 '의뢰부터 현장 증빙까지':'From request to field evidence','하나의 업무 흐름으로.':'One connected workflow.','로그아웃':'Log out','현장과 연결되는 업무':'Work connected to the field','닫기':'Close','워크스페이스를 불러오는 중입니다.':'Loading workspace…','현장 업무를 한눈에':'Your field work at a glance','오늘의 현장 업무':'Your field assignments','실행 현황 관리':'Execution overview','의뢰하고, 진행을 확인하고, 현장의 결과를 만나세요.':'Request work, track progress, and review results.','배정된 업무를 확인하고 현장의 기록을 전달하세요.':'Review your assignments and submit field records.','배정부터 Evidence 검증까지, 모든 실행을 관리하세요.':'Manage assignments and evidence review.','＋ 새 업무 의뢰':'+ New request',
 '조회된 업무':'Listed tasks','현재 페이지':'Current page','현장으로 연결된 업무':'Active field assignments','검증 대기':'Awaiting review','보고가 도착한 업무':'Tasks with reports','확인된 결과':'Confirmed results','건':'tasks','업무 목록':'Task list','↻ 새로고침':'↻ Refresh','전체':'All','업무 / Task ID':'Task / Task ID','수행 위치':'Work location','담당 Agent':'Assigned agent','상태':'Status','최근 업데이트':'Last updated','미배정':'Unassigned','상세':'details','아직 표시할 업무가 없습니다':'No tasks to display','새 업무를 의뢰해 첫 실행을 시작하세요.':'Create your first request.','배정 또는 상태 변경 후 새로고침해 주세요.':'Refresh after an assignment or status change.','이전':'Previous','페이지':'Page','다음':'Next','확인 중':'Checking',
 '현장과 연결되는':'Connect with the field.','가장 확실한 방법.':'See reliable results.','의뢰, 수행, 증빙, 검증.':'Request, execute, document, verify.','DOIT에서 하나의 흐름으로 이어집니다.':'A connected workflow with DOIT.','로그인':'Log in','이메일':'Email','이메일을 입력하세요':'Enter your email','비밀번호':'Password','비밀번호를 입력하세요':'Enter your password','확인 중…':'Checking…','워크스페이스 시작하기 →':'Open workspace →','초대받은 테스트 계정으로 로그인하세요.':'Sign in with your invited test account.',
 '← 업무 목록':'← Task list','의뢰 내용':'Request details','생성일':'Created','업무 시작':'Start work','요청사항':'Requirements','필요 Evidence':'Required evidence','목적지 지도 보기 ↗':'View destination map ↗','현장 Evidence':'Field evidence','아직 등록된 사진·동영상이 없습니다.':'No photos or videos have been uploaded.','회차':'Round','· 제외됨':'· Excluded','메모 없음':'No notes','미기록':'Not recorded','목적지 거리':'Distance to destination','계산 불가':'Unavailable','Evidence 정보':'Evidence details','촬영 시각:':'Captured:','GPS 수집:':'GPS recorded:','검증 기록':'Review history','회차 ·':'round ·','승인':'Approved','다음 단계':'Next step','자동 배정 가능한 Agent를 기다리고 있습니다.':'Waiting for an available agent.','수행 완료 / 보고 제출':'Finish work / Submit report','재수행 사유':'Reason for rework','결과 확인 / 완료':'Confirm results / Complete','진행 상황과 제출된 결과를 확인할 수 있습니다.':'You can review progress and submitted results.','클라이언트에게 보고가 전달되었습니다. 결과 확인을 기다리고 있습니다.':'Report sent to the client. Awaiting confirmation.','검토가 완료되었습니다. 클라이언트의 결과 확인을 기다리고 있습니다.':'Reviewed. Awaiting client confirmation.','✓ 업무가 완료되었습니다':'✓ Task completed',
 '현재 위치를 확인하는 중…':'Finding your location…','GPS 기록 완료 · 정확도 ±':'GPS recorded · Accuracy ±','현장 기록 등록':'Add field record','사진 또는 동영상':'Photo or video','JPG · PNG · WEBP · MP4 · WEBM / 파일당 최대 25 MB. 여러 파일은 한 번씩 등록하세요.':'JPG · PNG · WEBP · MP4 · WEBM / Up to 25 MB per file. Upload files one at a time.','◎ 현재 GPS 기록':'◎ Record current GPS','현장 위치를 함께 기록해 주세요.':'Record the field location as well.','현장 메모':'Field notes','현장에서 확인한 내용을 작성하세요.':'Describe what you observed on site.','업로드 중…':'Uploading…',
 '입력 내용이 바뀌어 이전 AI 결과를 적용하지 않았습니다.':'The text changed, so the previous AI result was not applied.','결과 언어':'Output language','한국어':'한국어','AI 번역':'AI translation','AI 내용 정리':'Organize with AI','버튼을 누르면 이 텍스트만 Gemini에 전송됩니다. 사진·영상은 전송하지 않습니다. 4,000자 이내.':'Only this text is sent to Gemini when clicked. No photos or videos. Up to 4,000 characters.','AI가 텍스트를 처리하고 있습니다…':'AI is processing the text…','번역':'Translation','내용 정리':'Organized text','· 요청 언어:':'· Requested language:','사실과 번역을 확인해 주세요.':'Check facts and translation.','확인 후 적용':'Review and apply','요청 원문':'Original text','적용 전 원문 복원':'Restore original text','번역 언어':'Translation language','전체 번역 중…':'Translating all…','번역 표시 중':'Translation displayed','의뢰 전체 번역 / 一括翻訳':'Translate entire request','원문 보기 / 原文':'View original','제목·내용·요청사항·필요 증빙·수행 위치·주소를 함께 번역합니다. 원문은 보존됩니다. 항목별 AI 사용 한도가 적용됩니다.':'Translates the title, details, requirements, evidence needs, location, and address. Originals are preserved. AI limits apply per field.','AI 번역 ·':'AI translation ·','· 주소와 고유명사는 원문도 확인해 주세요.':'· Check original addresses and proper names too.','전체 번역을 적용하지 않았습니다.':'The full translation was not applied.',
 '목적지':'Destination','목적지와 Evidence 위치 지도':'Map of destination and evidence locations','지도 연결에 실패해 OpenStreetMap으로 표시합니다. 좌표 입력은 계속 사용할 수 있습니다.':'Map connection failed. Showing OpenStreetMap; coordinate input is still available.','MapTiler 지도':'MapTiler map','VWorld 지도':'VWorld map','OpenStreetMap 대체 지도':'OpenStreetMap fallback','지도 연결 중':'Connecting map','지도를 클릭하여 목적지를 선택하세요.':'Click the map to select the destination.','초록: 목적지 · 주황: Evidence 위치':'Green: destination · Orange: evidence location','지도를 준비하고 있습니다…':'Loading map…','이 브라우저에서 위치 기능을 사용할 수 없습니다.':'Location is unavailable in this browser.','위치 권한과 HTTPS 연결을 확인해 주세요. 이전 위치는 삭제되었습니다.':'Check location permission and HTTPS. The previous location was cleared.',
 '요청을 처리하지 못했습니다.':'Could not process the request.','AI 처리에 실패했습니다. 원문은 유지되며 자동 재시도하지 않습니다.':'AI processing failed. The original is preserved. No automatic retry.','오늘 AI 사용 한도에 도달했습니다. 원문으로 계속 작성할 수 있습니다.':'Daily AI limit reached. You can continue with the original text.','AI 연결 준비 중입니다. Vertex AI 인증 설정 후 사용할 수 있습니다.':'AI connection is being configured.'
};
const extra:Record<string,[string,string]>={
 '파일 선택':['ファイルを選択','Choose file'],'선택된 파일 없음':['ファイル未選択','No file selected'],'수행 보고':['作業報告','Execution report'],
 '현재 위치를 확인하고 있습니다…':['現在地を確認中…','Finding your location…'],
 '현재 위치를 사용할 수 없습니다. 주소를 검색해 주세요.':['現在地を利用できません。住所を検索してください。','Location unavailable. Please search an address.'],
 '현재 GPS 위치 · 주소를 검색해 업무 목적지를 지정하세요.':['現在のGPS位置 · 住所を検索して作業場所を指定してください。','Current GPS location · Search an address to set the destination.'],
 '현재 위치:':['現在地:','Current location:'],
 '위치 권한이 없거나 GPS를 확인하지 못했습니다. 주소를 검색해 주세요.':['位置情報を取得できません。住所を検索してください。','GPS unavailable or permission denied. Search an address.'],
 '주소가 바뀌었습니다. 다시 검색하거나 지도에서 목적지를 선택해 주세요.':['住所が変更されました。再検索するか地図で目的地を選択してください。','Address changed. Search again or select the destination on the map.'],
 '주소를 검색하고 있습니다…':['住所を検索中…','Searching address…'],
 '검색 위치로 지도를 이동했습니다. 주소와 핀을 확인한 뒤 아래 후보를 선택하거나 지도에서 목적지를 지정하세요.':['検索位置を表示しました。住所とピンを確認し、候補または地図で目的地を選択してください。','Map moved to search result. Check the address and pin, then choose a result or select on the map.'],
 '검색 결과가 없습니다. 국가와 상세 주소를 확인해 주세요.':['検索結果がありません。国と住所を確認してください。','No results. Check the country and full address.'],
 '목적지 좌표를 선택했습니다. 실제 방문 위치인지 확인해 주세요.':['目的地を選択しました。実際の訪問場所か確認してください。','Destination selected. Confirm the actual visit location.'],
 '새 현장 업무 의뢰':['新しい現地業務の依頼','New field work request'],'취소':['キャンセル','Cancel'],'업무 제목':['業務名','Task title'],'예: 매장 입구 및 운영 상태 확인':['例：店舗入口と営業状況の確認','Example: Check store entrance and operating status'],'업무 설명':['業務内容','Task description'],'현장에서 확인해야 할 내용을 구체적으로 작성해 주세요.':['現地で確認する内容を具体的に入力してください。','Describe exactly what should be checked on site.'],'장소 이름':['場所の名前','Place name'],'검색 국가':['検索対象国','Search country'],'전체 국가':['すべての国','All countries'],'일본':['日本','Japan'],'대한민국':['韓国','South Korea'],'미국':['米国','United States'],'영국':['英国','United Kingdom'],'싱가포르':['シンガポール','Singapore'],'주소':['住所','Address'],'일본어·영어·한국어 주소를 그대로 입력하세요':['日本語・英語・韓国語の住所を入力','Enter a Japanese, English, or Korean address'],'주소 검색':['住所検索','Search address'],'주소 입력 후 돋보기를 누르면 해당 위치로 지도가 이동합니다.':['住所を入力して検索ボタンを押すと地図が移動します。','Enter an address and click search to move the map.'],'일부 주소만 일치 ·':['住所の一部のみ一致 ·','Partial address match ·'],'건물 수준 위치':['建物の位置','Building location'],'주소 후보 · 입력 주소와 일치하는지 확인':['住所候補 · 入力住所との一致を確認','Address candidate · Check against your input'],'지역 수준 후보 · 정확한 주소 위치가 아닐 수 있음':['地域の候補 · 正確な住所ではない場合があります','Area candidate · May not be the exact address'],'아직 업무 목적지가 확정되지 않았습니다.':['作業場所はまだ確定していません。','Task destination is not confirmed yet.'],'현재 위치를 기다리는 중입니다. 주소를 검색해 지도를 열 수도 있습니다.':['現在地を取得中です。住所検索でも地図を表示できます。','Waiting for location. You can also search an address to open the map.'],'방문 시간, 유의사항 등':['訪問時間、注意事項など','Visit time, precautions, etc.'],'필요 사진·동영상':['必要な写真・動画','Required photos / videos'],'촬영할 대상과 구도를 알려 주세요.':['撮影対象と構図を指定してください。','Describe subjects and angles to capture.'],'등록 중…':['登録中…','Submitting…'],'의뢰 등록 →':['依頼を登録 →','Submit request →'],
 '보고 내용을 번역하고 있습니다…':['報告内容を翻訳中…','Translating report…'],'AI 번역 · 원문과 사실을 확인해 주세요.':['AI翻訳 · 原文と事実を確認してください。','AI translation · Check the original and facts.'],'번역 보고 보기':['翻訳された報告を表示','View translated report'],'보고 원문 보기':['報告の原文を表示','View original report'],'번역을 완료하지 못해 원문을 표시합니다.':['翻訳できなかったため原文を表示しています。','Translation incomplete. Showing original text.'],'번역 다시 요청':['翻訳を再試行','Retry translation']
};
for(const [key,[ja,en]] of Object.entries(extra)){japanese[key]=ja;english[key]=en;}
export type UILanguage='ko'|'ja'|'en';
function initialLanguage():UILanguage{
 try{const saved=localStorage.getItem('doit-language-'+location.pathname.split('/')[1]);if(saved==='ko'||saved==='ja'||saved==='en')return saved;}catch{}
 return location.pathname.startsWith('/agent')?'ja':'ko';
}
export const uiLanguage=initialLanguage();
document.documentElement.lang=uiLanguage;
export function changeLanguage(language:string){if(language!=='ko'&&language!=='ja'&&language!=='en')return;try{localStorage.setItem('doit-language-'+location.pathname.split('/')[1],language)}catch{}location.reload();}
export function tr(text:string){const key=text.trim(),value=uiLanguage==='ja'?japanese[key]:uiLanguage==='en'?english[key]:undefined;return value===undefined?text:text.replace(key,value);}
