import {useEffect,useState} from 'react';
import {api,role,type User} from './api';
import {tr} from './i18n';
type Notice={id:string;task_id:string;title:string;action:string;read_at:string|null;created_at:string};
const labels:Record<string,string>={AGENT_AUTO_ASSIGNED:'새 업무가 배정되었습니다.',REPORT_SUBMITTED:'보고서가 도착했습니다.',REEXECUTION_REQUESTED:'재수행 요청이 도착했습니다.',TASK_COMPLETED:'의뢰인이 업무를 완료했습니다.'};
export function Notifications({open}:{open:(id:string)=>void}){
 const [data,setData]=useState<{items:Notice[];unread:number}>({items:[],unread:0}),[error,setError]=useState('');
 useEffect(()=>{let active=true;async function refresh(){try{const d=await api<typeof data>('/notifications');if(active){setData(d);setError('');}}catch(e){if(active)setError((e as Error).message)}}void refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh()},30000);return()=>{active=false;clearInterval(timer)}},[]);
 return <details className="panel content notifications"><summary>{tr('알림')} · {data.unread} {tr('읽지 않음')}</summary>{error&&<p role="alert">{error}</p>}{!data.items.length&&<p>{tr('새 알림이 없습니다.')}</p>}{data.items.map(n=><button key={n.id} className={n.read_at?'read':'unread'} onClick={async()=>{try{await api('/notifications/'+n.id+'/read',{});setData(d=>({...d,unread:Math.max(0,d.unread-(n.read_at?0:1)),items:d.items.map(i=>i.id===n.id?{...i,read_at:new Date().toISOString()}:i)}));open(n.task_id)}catch(e){setError((e as Error).message)}}}><strong>{tr(labels[n.action]||n.action)}</strong><span>{n.title}</span><small>{new Date(n.created_at).toLocaleString()}</small></button>)}</details>;
}
export function AccountSettings({logout}:{logout:()=>void}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <details className="panel content"><summary>{tr('계정 설정')}</summary><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form);if(data.get('password')!==data.get('confirm')){setError(tr('새 비밀번호가 일치하지 않습니다.'));return;}setBusy(true);setError('');try{await api('/auth/password',{current_password:data.get('current_password'),password:data.get('password')});form.reset();logout();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label>{tr('현재 비밀번호')}<input name="current_password" type="password" autoComplete="current-password" required/></label><label>{tr('새 비밀번호 (12자 이상)')}<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={256} required/></label><label>{tr('새 비밀번호 확인')}<input name="confirm" type="password" autoComplete="new-password" required/></label><button disabled={busy}>{tr('비밀번호 변경 후 다시 로그인')}</button>{error&&<p role="alert">{error}</p>}</form></details>;
}
export function RedeemAccount(){const [busy,setBusy]=useState(false),[message,setMessage]=useState('');return <details className="panel content"><summary>{tr('초대 수락 / 비밀번호 복구')}</summary><p className="hint">{tr('관리자에게 받은 일회용 코드를 입력하세요.')}</p><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);if(f.get('password')!==f.get('confirm')){setMessage(tr('새 비밀번호가 일치하지 않습니다.'));return;}setBusy(true);try{await api('/auth/redeem',{code:String(f.get('code')).trim(),password:f.get('password')});form.reset();setMessage(tr('비밀번호 설정 완료. 로그인해 주세요.'));}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}}><label>{tr('일회용 코드')}<input name="code" autoComplete="off" required/></label><label>{tr('새 비밀번호 (12자 이상)')}<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={256} required/></label><label>{tr('새 비밀번호 확인')}<input name="confirm" type="password" autoComplete="new-password" required/></label><button disabled={busy}>{tr('비밀번호 설정')}</button><p role="status">{message}</p></form></details>;}
type ManagedUser=User&{active:number};
export function Administration(){
 const [users,setUsers]=useState<ManagedUser[]>([]),[password,setPassword]=useState(''),[error,setError]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[backups,setBackups]=useState<{id:string;started_at:string;status:string;detail:string}[]>([]);
 async function refresh(){setUsers(await api<ManagedUser[]>('/admin/users'));setBackups(await api<typeof backups>('/admin/backups'));}
 useEffect(()=>{void refresh().catch(e=>setError(e.message))},[]);
 async function act(body:Record<string,unknown>){setBusy(true);setError('');setCode('');try{const result=await api<{code?:string;expires_hours?:number}>('/admin/accounts',{...body,current_password:password});if(result.code)setCode(result.code+'\n'+tr('유효 시간')+': '+result.expires_hours+'h');setPassword('');await refresh();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <details className="panel content"><summary>{tr('사용자 / 운영 관리')}</summary><p className="hint">{tr('초대·복구 코드는 직접 전달하세요. 시스템에서 이메일을 발송하지 않습니다.')}</p><label>{tr('관리자 현재 비밀번호')}<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><form onSubmit={e=>{e.preventDefault();void act({action:'invite',...Object.fromEntries(new FormData(e.currentTarget))});}}><label>{tr('이름')}<input name="name" required maxLength={100}/></label><label>{tr('이메일')}<input name="email" type="email" required maxLength={200}/></label><label>{tr('역할')}<select name="role"><option value="CLIENT">{tr('의뢰인')}</option><option value="AGENT">{tr('에이전트')}</option></select></label><button disabled={busy||!password}>{tr('초대 코드 발급')}</button></form>{code&&<div className="recovery-code"><p>{tr('한 번만 표시됩니다. 안전한 방법으로 본인에게 전달하세요.')}</p><pre>{code}</pre><button onClick={()=>setCode('')}>{tr('닫기')}</button></div>}{error&&<p role="alert">{error}</p>}<div className="account-list">{users.map(u=><div key={u.id}><strong>{u.name}</strong> · {u.email} · {u.role} · {tr(u.active?'활성':'비활성 / 초대 대기')}{u.role!=='ADMIN'&&<div className="button-row"><button disabled={busy||!password} onClick={()=>void act({action:'reset',user_id:u.id})}>{tr('복구 / 초대 재발급')}</button><button disabled={busy||!password} onClick={()=>void act({action:'active',user_id:u.id,active:!u.active})}>{tr(u.active?'계정 비활성화':'계정 활성화')}</button></div>}</div>)}</div><h3>{tr('자동 백업 기록')}</h3>{!backups.length?<p>{tr('아직 백업 실행 기록이 없습니다.')}</p>:backups.map(b=><p key={b.id}>{b.started_at} · {b.status}<br/>{b.detail}</p>)}</details>;
}
